### ISSUE TITLE
Change of the name

### ISSUE THREAD

**Issue by klokan** [Fedik/php-maptiler#2]
Could you please choose a different name for the utility?

MapTiler is normally related to the software available at http://www.maptiler.com/ - and the name of your utility is confusing some people now... we have got related emails.

This is just a kind query of a fellow - not a legal request or so...

Hopefully it is possible for you - thanks!

**Comment by jcrombez** [comment]
I guess my recent pull request refreshed the visibility of this project. Supprising how fast people contact you about this.

I think i would have never found it in the first place without its current name.
The combination of "map" and "tiler" is quite common when you need a tool to generate tiles for a map.
I also found your commercial project, i added "php" hopping to find something free and open, with success.

Just a suggestion, maybe a simple disclaimer would be enough ? or people are that dumb ?

**Comment by Fedik** [comment]
Name is different, it is `php-maptiler`, not `maptiler` :smile: 
Project not under active development, I just share script that I made for one of my projects....
and it already 2 year old, I see not much sense for rename, sorry

@klokan if you gets more clients, you need to be happy :wink:  
example you could suggest them your better solution

**Comment by Fedik** [comment]
I added the "Attention" section in to readme https://github.com/Fedik/php-maptiler#attention
hope it will make you happy :wink:

**Comment by klokan** [comment]
Thanks for the fast reply and the added "Attention" section. If there could be a link to the original MapTiler project it would be nice.
Whether to change the name or not is your decision.
