### ISSUE TITLE
zoom_max limited to 4

### ISSUE THREAD

**Issue by jcrombez** [Fedik/php-maptiler#3]
Even if i set a higher value than 4, the script ends up with 4 levels of zoom (in reality 5 :  0, 1, 2, 3, 4).

I tried to find the problem but i'm not familiar enough with the code yet.

I think the problem is related to this line : https://github.com/Fedik/php-maptiler/blob/master/maptiler.php#L220

It's where the value turn from what i provided to 4.

**Comment by Fedik** [comment]
it is not a :bug: it feature :wink: 

by default script prepare the image for each zoom  level untill image size is enough,
so if image size smaller than need for zoom 4, script stops on zoom 3,

in your case the image size smaller than need for zoom 5, so script stops on 4

you can force script to resize image to fit zoom 5 (or even bigger), 
for this need set option `scaling_up = 5`, so it will resize the image until zoom 5, 
or `scaling_up = 8` - and it will resize the image until zoom 8 ... and so on

**Comment by jcrombez** [comment]
Makes sense, thank you :)
