### ISSUE TITLE
Question: Hosting of map tiles

### ISSUE THREAD

**Issue by iamromeo** [Fedik/php-maptiler#4]
Hey Fadik,

I have been looking over your script and i was wondering if you know of any place/service I would store the tiles after they are created so I can use them from there or if you have an implementation that could save on AWS S3?

**Comment by Fedik** [comment]
no, sorry,
I have used it on the same server where the script, and have not searched for such services,

**Comment by iamromeo** [comment]
Thank you make - much appreciated the answer - Great script! Keep it up :+1:
