### ISSUE TITLE
Forcing to start from top left corner

### ISSUE THREAD

**Issue by CodilX** [Fedik/php-maptiler#5]
I'm trying to generate a map and the contents are tiled to be exactly 256 single colored blocks. I want to overlay a grid over them, but when I generate the map the grid gets offset. I noticed that a huge block is put at the top of the map when generating it. 

Can I force the extra generated area to be placed at the bottom so that it would retain my starting position at the top left corner?

**Comment by Fedik** [comment]
I do not remember,
try different `tms` option: `true` or `false`

**Comment by CodilX** [comment]
Thank you!
