### ISSUE TITLE
All images are offset

### ISSUE THREAD

**Issue by Warface** [Fedik/php-maptiler#6]
I have an image 2048x2048 and creating tiles of 256x256 with a zoom level of 4.

The script creates it well but Google Maps seems to handle them weirdly, they're all messed up and gets less better when zooming

![untitled-1](https://user-images.githubusercontent.com/726190/47366839-804c4080-d6ac-11e8-8444-0581681070d4.jpg)

**Comment by Fedik** [comment]
Google map uses XYZ tiles, instead of TMS tiles.
try use `'tms' => false` option, when generate tiles
