### ISSUE TITLE
width or height exceeds limit `....../mapImage.png' @ error/cache.c/OpenPixelCache/3911

### ISSUE THREAD

**Issue by kiiraklis94** [Fedik/php-maptiler#7]
Though it was working fine as part of a laravel application that is hosted locally, when I moved it to an Ubuntu server it gives me this error.

I tried it with images of various sizes (down to 150x150) and it still gives me the same error.

Thanks.

**Comment by Fedik** [comment]
This is because of server configuration for ImageMagick. I suspect ImageMagick policy.xml

Here nothing that can be fixed on our side.
